/**
 * Osler content loader — fetches content from category manifests.
 *
 * Cloud-enabled instances prefer the Worker's R2-backed endpoints and fall
 * back to bundled /osler-content/ content when the remote source is offline.
 * Non-cloud instances read directly from the bundled directory.
 *
 * Each category has a manifest.json (auto-generated by scripts/generate-content-manifests.js)
 * describing a tree of ContentTreeNode objects. Leaf nodes correspond to folders
 * containing one or more .json data files whose arrays are merged on load.
 */

import type {
  AnyContent,
  BankContent,
  EngineType,
  FlashcardContent,
  OsceContent,
  QuizContent,
  WrittenContent,
  MixedContent,
  ContentTreeNode,
  CategoryManifest,
  Flashcard,
  FlashcardSubdeck,
  VideoContent,
} from "./types";
import { isEngineEnabled, getEngineOverride, enabledEngines, loadConfig } from "./config";
import { onContentVersionChange, currentContentVersion } from "./content-version";
import { clearArticlesCache } from "./articles";
import { clearVideosCache } from "./videos";
import {
  manifestUrl,
  contentFileUrl,
  localContentUrl,
  localManifestUrl,
  packBasePath as resolvePackBasePath,
  cacheBust,
} from "./content-url";

let hasWarnedAboutRemoteFallback = false;
let remoteContentUnavailable = false;

export { fetchWithLocalFallback as fetchWithLocalFallback };

async function fetchWithLocalFallback(primaryUrl: string, fallbackUrl: string): Promise<Response> {
  // Respect HTTP cache headers so revisiting a hub does not re-download its
  // manifest or pack files. clearContentCache() remains the explicit refresh.
  if (primaryUrl !== fallbackUrl && remoteContentUnavailable) {
    return fetch(fallbackUrl);
  }

  let response: Response;
  try {
    response = await fetch(primaryUrl);
  } catch (error) {
    // Only a network-level failure (offline, DNS, CORS, worker down) makes the
    // remote source unavailable. Latch so the rest of the session stops
    // hammering a dead remote and reads bundled content instead.
    if (primaryUrl === fallbackUrl) throw error;
    remoteContentUnavailable = true;
    if (!hasWarnedAboutRemoteFallback) {
      hasWarnedAboutRemoteFallback = true;
      console.warn("Remote content is unavailable; using bundled content.", error);
    }
    return fetch(fallbackUrl);
  }

  if (response.ok || primaryUrl === fallbackUrl) return response;

  // A non-ok HTTP status (e.g. 404 for one missing file) means the remote is
  // reachable but the specific resource is absent — fall back to bundled for
  // THIS request only. Do NOT latch: other remote resources may still exist.
  const fallbackResponse = await fetch(fallbackUrl);
  if (!fallbackResponse.ok) {
    throw new Error(`Fallback request failed with status ${fallbackResponse.status}`);
  }
  return fallbackResponse;
}

/* ── Category helpers ─────────────────────────────────────────────── */

const CATEGORY_PATHS: Record<string, string> = {
  quiz: "qbank",
  bank: "qbank",
  written: "qbank",
  mixed: "qbank",
  flashcard: "flashcard",
  osce: "osce",
  library: "library",
  video: "videos",
};

function categoryFolder(type: EngineType): string {
  return CATEGORY_PATHS[type] ?? type;
}

/**
 * Base URL for a content node's folder (used to build precache URLs).
 */
export function packBasePath(node: ContentTreeNode): string {
  const folder = categoryFolder(node.type || inferTypeFromFiles(node.files ?? []));
  return resolvePackBasePath(folder, node.path);
}

/**
 * All cacheable URLs for a leaf node: its data files plus any images in its
 * `images/` subfolder. Returns an empty array for branch nodes.
 * Each URL is cache-busted with `?v=` when a content version is known so
 * the SW CacheFirst path treats it as immutable (bandwidth/Worker win).
 */
export function nodeUrls(node: ContentTreeNode): string[] {
  if (node.items.length > 0) return [];
  const base = packBasePath(node);
  // packBasePath is a directory prefix (no ?v=) — bust the final file URLs.
  function bust(url: string): string {
    const v = currentContentVersion();
    if (!v || url.includes("v=")) return url;
    return `${url}${url.includes("?") ? "&" : "?"}v=${encodeURIComponent(v)}`;
  }
  const urls = (node.files ?? []).map((f) => bust(`${base}${f}`));
  for (const img of node.images ?? []) urls.push(bust(`${base}images/${img}`));
  return urls;
}

/**
 * All cacheable URLs for a node and — for branch nodes — every leaf
 * descendant: data files plus images/ entries. Single source of truth for
 * the offline download buttons and the session precache path.
 */
export function collectPackUrls(node: ContentTreeNode): string[] {
  const urls = nodeUrls(node);
  for (const child of node.items) urls.push(...collectPackUrls(child));
  return urls;
}

/**
 * Uids of every leaf under a node (or the node itself when it is a leaf).
 * Used for progress rollups and flashcard due-count aggregation.
 */
export function collectLeafUids(node: ContentTreeNode): string[] {
  if (node.items.length === 0) return [node.uid];
  return node.items.flatMap(collectLeafUids);
}

/* ── Tree loading ─────────────────────────────────────────────────── */

/** Shared in-flight and resolved manifest requests for the current session. */
const manifestTreeMemo = new Map<string, Promise<ContentTreeNode[]>>();
const manifestTreeSyncCache = new Map<string, ContentTreeNode[]>();

async function loadManifestTree(folder: string): Promise<ContentTreeNode[]> {
  await loadConfig();
  const cachedSync = manifestTreeSyncCache.get(folder);
  if (cachedSync) return cachedSync;

  const cached = manifestTreeMemo.get(folder);
  if (cached) return cached;

  const promise = (async () => {
    const res = await fetchWithLocalFallback(manifestUrl(folder), localManifestUrl(folder));
    if (!res.ok) throw new Error(`Failed to load ${folder}/manifest.json: ${res.status}`);
    const manifest = (await res.json()) as CategoryManifest;
    const items = unwrapCategoryDuplicateRoots(manifest.items, folder);
    manifestTreeSyncCache.set(folder, items);
    return items;
  })();
  manifestTreeMemo.set(folder, promise);
  try {
    const items = await promise;
    manifestTreeSyncCache.set(folder, items);
    return items;
  } catch (error) {
    manifestTreeMemo.delete(folder);
    manifestTreeSyncCache.delete(folder);
    throw error;
  }
}

/**
 * Load the category manifest (tree) for a given engine type. The URL is
 * resolved by cloud config. If the remote source is unavailable, the bundled
 * manifest keeps local study sessions usable.
 */
export async function loadCategoryTree(type: EngineType): Promise<ContentTreeNode[]> {
  return loadManifestTree(categoryFolder(type));
}

/**
 * Synchronous getter for category trees already resolved into memory.
 * Used by tab views on mount to render immediately without flashing a skeleton.
 */
export function getCachedCategoryTree(type: EngineType): ContentTreeNode[] | null {
  return manifestTreeSyncCache.get(categoryFolder(type)) ?? null;
}

/**
 * Synchronously retrieve all enabled leaf nodes if their trees are in memory.
 */
export function getCachedAllCategoryLeaves(): ContentTreeNode[] | null {
  const types = enabledEngines().filter((t) => t !== "library");
  const folders = [...new Set(types.map(categoryFolder))];
  const allCached = folders.every((f) => manifestTreeSyncCache.has(f));
  if (!allCached) return null;
  const byUid = new Map<string, ContentTreeNode>();
  for (const f of folders) {
    const items = manifestTreeSyncCache.get(f) ?? [];
    for (const leaf of flattenTree(items)) {
      byUid.set(leaf.uid, leaf);
    }
  }
  return [...byUid.values()];
}

/**
 * R2 content dropped with the category folder itself inside the selection
 * (e.g. dragging a `library/` folder into the library destination) lands at
 * `content-files/library/library/...`, and the manifest then wraps the whole
 * category under a phantom "library" root. Hoist such nodes' children so the
 * tree starts at the real folders; paths and uids are preserved verbatim so
 * content URLs and progress keys stay stable. Nodes carrying their own files
 * are left untouched — nothing is dropped.
 */
function unwrapCategoryDuplicateRoots(nodes: ContentTreeNode[], folder: string): ContentTreeNode[] {
  return nodes.flatMap((node) =>
    (node.files?.length ?? 0) === 0 && node.path.replace(/\/$/, "") === folder ? node.items : [node]
  );
}

/**
 * Flatten a content tree to a list of leaf nodes.
 * Skips asset subdirectories (images/, assets/) that may appear as nodes
 * from Worker-generated manifests but contain no content data.
 */
const ASSET_DIR_NAMES = new Set(["images", "assets"]);

export function flattenTree(nodes: ContentTreeNode[]): ContentTreeNode[] {
  const leaves: ContentTreeNode[] = [];
  function walk(list: ContentTreeNode[]) {
    for (const node of list) {
      const lastSeg = node.path.replace(/\/$/, "").split("/").pop() ?? "";
      if (ASSET_DIR_NAMES.has(lastSeg)) continue;
      if (node.items.length === 0) {
        leaves.push(node);
      } else {
        walk(node.items);
      }
    }
  }
  walk(nodes);
  return leaves;
}

/* ── Content loading from leaf folders ───────────────────────────── */

/** Infer engine type from a node's data file names when node.type is missing. */
const FILE_TYPE_KEYS: Record<string, EngineType> = {
  questions: "quiz", passages: "bank", prompts: "written",
  cards: "flashcard", videos: "video", stations: "osce",
};

function inferTypeFromFiles(files: string[]): EngineType {
  for (const f of files) {
    const base = f.replace(/\.[^.]+$/, "");
    if (FILE_TYPE_KEYS[base]) return FILE_TYPE_KEYS[base];
  }
  return "quiz";
}

/**
 * Load content from a leaf node's folder by fetching all its .json data files
 * and merging their arrays. The preferred base URL is resolved by cloud
 * config, with the bundled pack used when the remote source is unavailable.
 */
export async function loadNodeContent(node: ContentTreeNode): Promise<AnyContent> {
  await loadConfig();
  const effectiveType = node.type || inferTypeFromFiles(node.files ?? []);
  const folder = categoryFolder(effectiveType);
  if (!folder) throw new Error(`Cannot resolve folder for node type: ${node.type}`);
  const dataFiles = (node.files ?? []).filter((f) => f.endsWith(".json"));
  if (dataFiles.length === 0) {
    throw new Error(`No JSON data files in ${node.path}`);
  }

  // Build file URLs via the version-aware helper so both primary and fallback
  // carry `?v=` when a publish has bumped the content version. Using the
  // per-file contentFileUrl (not base+file) guarantees the `?v=` lands after
  // the filename and the SW CacheFirst path treats it as immutable.
  const results = await Promise.all(
    dataFiles.map(async (file) => {
      const primary = contentFileUrl(folder, `${node.path}${file}`);
      const fallback = cacheBust(localContentUrl(folder, `${node.path}${file}`));
      const res = await fetchWithLocalFallback(primary, fallback);
      if (!res.ok) throw new Error(`Failed to load ${primary}: ${res.status}`);
      return (await res.json()) as Record<string, unknown>;
    })
  );

  // Merge all data arrays and preserve scalar fields like `type`
  const merged: Record<string, unknown[]> = {};
  for (const data of results) {
    for (const [key, val] of Object.entries(data)) {
      if (Array.isArray(val)) {
        if (!merged[key]) merged[key] = [];
        merged[key].push(...val);
      } else if (typeof val === "string" && key === "type") {
        // Preserve explicit `type` field from data file
        merged[key] = [val] as unknown[];
      }
    }
  }

  return buildContent(node, merged, effectiveType);
}

/**
 * Build an AnyContent object from a leaf node and merged data arrays.
 */
function buildContent(node: ContentTreeNode, data: Record<string, unknown[]>, effectiveType?: EngineType): AnyContent {
  // Use explicit `type` from data file if present, otherwise fall back to effectiveType, then node.type
  const explicitType = data.type?.[0] as EngineType | undefined;
  let nodeType = explicitType || effectiveType || node.type || "quiz";

  // Auto-detect mixed content if not already set but contains both questions and prompts
  if (nodeType !== "flashcard" && nodeType !== "osce" && nodeType !== "video") {
    const hasMCQs = (data.questions && data.questions.length > 0) || (data.passages && data.passages.length > 0);
    const hasWritten = data.prompts && data.prompts.length > 0;
    if (hasMCQs && hasWritten) {
      nodeType = "mixed";
    }
  }

  const meta = {
    uid: node.uid,
    title: node.title,
    description: `Content pack: ${node.title}`,
    lang: node.lang ?? "en",
  };

  const chapters = data.chapters as unknown as BankContent["chapters"];

  switch (nodeType) {
    case "flashcard": {
      const cards = (data.cards ?? []) as Flashcard[];
      // If this node has children (branch node), they become subdecks
      const subdecks: FlashcardSubdeck[] | undefined = node.items.length > 0
        ? node.items.map((child) => ({
            id: child.uid,
            title: child.title,
            parentId: node.uid,
          }))
        : undefined;
      return { meta, type: "flashcard", cards, subdecks } as FlashcardContent;
    }
    case "quiz":
      return {
        meta,
        type: "quiz",
        chapters,
        questions: data.questions ?? [],
        prompts: data.prompts as unknown as QuizContent["prompts"],
      } as QuizContent;
    case "bank":
      return {
        meta,
        type: "bank",
        chapters,
        passages: data.passages as unknown as BankContent["passages"],
        questions: data.questions as unknown as BankContent["questions"],
        prompts: data.prompts as unknown as BankContent["prompts"],
      } as BankContent;
    case "written":
      return {
        meta,
        type: "written",
        chapters,
        prompts: data.prompts ?? [],
        questions: data.questions as unknown as WrittenContent["questions"],
      } as WrittenContent;
    case "mixed":
      return {
        meta,
        type: "mixed",
        chapters,
        passages: data.passages as unknown as MixedContent["passages"],
        questions: data.questions as unknown as MixedContent["questions"],
        prompts: data.prompts as unknown as MixedContent["prompts"],
      } as MixedContent;
    case "osce":
      return { meta, type: "osce", stations: data.stations ?? [] } as OsceContent;
    case "video":
      return { meta, type: "video", videos: data.videos ?? [] } as VideoContent;
    default:
      throw new Error(`Unknown content type: ${nodeType}`);
  }
}

/* ── High-level loading ───────────────────────────────────────────── */

/**
 * Walk all category manifests and load all leaf content.
 * Returns both flat items list and per-category trees.
 */
/**
 * Load the category manifests (trees) for every enabled engine, keyed by
 * engine type. Library articles are .md files loaded via articles.ts, not
 * JSON, so they are excluded. No content files are fetched — hub views can
 * paint entries from the manifest alone (titles, itemCount, lang).
 */
export async function loadCategoryTrees(): Promise<Record<string, ContentTreeNode[]>> {
  await loadConfig();
  const trees: Record<string, ContentTreeNode[]> = {};
  for (const type of enabledEngines().filter((t) => t !== "library")) {
    const folder = categoryFolder(type);
    if (!folder) continue;
    try {
      // Multi-type folders (qbank hosts quiz/bank/written) map to one
      // manifest, memoized per folder, so each type shares the tree.
      trees[type] = await loadManifestTree(folder);
    } catch {
      // ignore missing manifests
    }
  }
  return trees;
}

/**
 * Load manifests AND leaf content for an explicit set of engine types.
 * Scoped by the caller (the global search index builds from all enabled
 * engines, on demand) so no hub render path ever fetches unrelated
 * categories.
 */
export async function loadContentForTypes(types: EngineType[]): Promise<{
  items: Array<{ node: ContentTreeNode; content: AnyContent | null }>;
  trees: Record<string, ContentTreeNode[]>;
}> {
  await loadConfig();
  const trees = await loadCategoryTrees();
  const allLeaves: ContentTreeNode[] = [];
  const folders = new Set(types.map(categoryFolder).filter(Boolean) as string[]);
  for (const folder of folders) {
    try {
      allLeaves.push(...flattenTree(await loadManifestTree(folder)));
    } catch {
      // ignore missing manifests
    }
  }

  const items = await Promise.all(
    allLeaves.map(async (node) => {
      try {
        const content = await loadNodeContent(node);
        return { node, content };
      } catch (e) {
        console.warn(`Failed to load ${node.path}:`, e);
        return { node, content: null };
      }
    })
  );
  return { items, trees };
}

/**
 * Session-scoped memo of loaded content packs, keyed by uid.
 *
 * Capped at MAX_CACHE_ENTRIES with LRU eviction — when the cache is full,
 * the least-recently-accessed entry is deleted before inserting a new one.
 * This prevents unbounded memory growth during long sessions while still
 * avoiding re-downloads for back/forward navigation.
 *
 * NOTE: entries are never silently invalidated. If R2 content changes
 * (admin publishes new content), call `clearContentCache()` to drop the
 * in-memory copies so the next load re-fetches from the source.
 */
const MAX_CACHE_ENTRIES = 50;
const contentCacheMemo = new Map<string, AnyContent>();

function cacheGet(uid: string): AnyContent | undefined {
  const value = contentCacheMemo.get(uid);
  if (value !== undefined) {
    // Move to end (most recently used) by re-inserting.
    contentCacheMemo.delete(uid);
    contentCacheMemo.set(uid, value);
  }
  return value;
}

function cacheSet(uid: string, content: AnyContent): void {
  if (contentCacheMemo.size >= MAX_CACHE_ENTRIES) {
    // Evict the oldest entry (first key in insertion order).
    const oldest = contentCacheMemo.keys().next().value;
    if (oldest !== undefined) contentCacheMemo.delete(oldest);
  }
  contentCacheMemo.set(uid, content);
}

/**
 * Session-scoped memo of content nodes, keyed by uid. Lets callers that load
 * a pack by uid (e.g. rebuilding a saved session's pool) also resolve the
 * node's path/category for asset URLs without a second manifest fetch.
 */
const nodeCacheMemo = new Map<string, ContentTreeNode>();

function nodeCacheGet(uid: string): ContentTreeNode | undefined {
  const value = nodeCacheMemo.get(uid);
  if (value !== undefined) {
    nodeCacheMemo.delete(uid);
    nodeCacheMemo.set(uid, value);
  }
  return value;
}

function nodeCacheSet(uid: string, node: ContentTreeNode): void {
  if (nodeCacheMemo.size >= MAX_CACHE_ENTRIES) {
    const oldest = nodeCacheMemo.keys().next().value;
    if (oldest !== undefined) nodeCacheMemo.delete(oldest);
  }
  nodeCacheMemo.set(uid, node);
}

/** Clear the content cache (call after admin content changes). */
export function clearContentCache(): void {
  remoteContentUnavailable = false;
  hasWarnedAboutRemoteFallback = false;
  contentCacheMemo.clear();
  nodeCacheMemo.clear();
  manifestTreeMemo.clear();
  manifestTreeSyncCache.clear();
  try {
    clearArticlesCache();
  } catch {}
  try {
    clearVideosCache();
  } catch {}
}

/* ── Freshness ────────────────────────────────────────────────────── */

// A moved content version means remote manifests changed: drop every cached
// tree/pack so the next load re-fetches (with the new ?v= stamp) instead of
// rendering what the previous version served. Registered once per session —
// startContentVersionSync() (app shell) drives the version checks.
if (typeof window !== "undefined") {
  onContentVersionChange(() => {
    clearContentCache();
  });
}

/**
 * Locate a content node by uid across every enabled engine's category
 * manifest. Returns the node so callers can resolve its folder path and
 * category for asset URLs (question images, flashcard images, etc.) when
 * rebuilding content they don't otherwise have a handle to — e.g. reopening
 * a saved quiz session. Falls back to an unbounded search when an
 * `engineHint` misses, mirroring `loadContentByUid`.
 */
export async function loadNodeByUid(uid: string, engineHint?: EngineType): Promise<ContentTreeNode> {
  await loadConfig();
  const cached = nodeCacheGet(uid);
  if (cached) return cached;

  const types = enabledEngines().filter((t) => t !== "library");

  let folders: string[] = [];
  if (engineHint) {
    folders = [categoryFolder(engineHint)];
  } else {
    folders = Array.from(new Set(types.map(categoryFolder)));
  }

  for (const folder of folders) {
    try {
      const manifestItems = await loadManifestTree(folder);
      const found = findNodeByUid(manifestItems, uid);
      if (found) {
        nodeCacheSet(uid, found);
        return found;
      }
    } catch {
      continue;
    }
  }

  if (engineHint) {
    return loadNodeByUid(uid);
  }

  throw new Error(`Content not found: ${uid}`);
}

export async function loadContentByUid(uid: string, engineHint?: EngineType): Promise<AnyContent> {
  const cached = cacheGet(uid);
  if (cached) {
    return cached;
  }

  const node = await loadNodeByUid(uid, engineHint);
  const content = await loadNodeContent(node);
  cacheSet(uid, content);
  return content;
}

/**
 * Search a tree for a node by uid.
 */
export function findNodeByUid(nodes: ContentTreeNode[], uid: string): ContentTreeNode | null {
  for (const node of nodes) {
    if (node.uid === uid) return node;
    if (node.items.length > 0) {
      const found = findNodeByUid(node.items, uid);
      if (found) return found;
    }
  }
  return null;
}

/**
 * Convert a ContentTreeNode to a simple object for passing as props.
 * (Keeps interface compatibility where ManifestItem was used.)
 */
export function nodeToItem(node: ContentTreeNode): {
  uid: string;
  type: EngineType;
  title: string;
  path: string;
} {
  return {
    uid: node.uid,
    type: node.type,
    title: node.title,
    path: node.path,
  };
}

/* ── Type guards ────────────────────────────────────────────────────── */
export function isQuiz(c: AnyContent): c is QuizContent {
  return c.type === "quiz";
}
export function isBank(c: AnyContent): c is BankContent {
  return c.type === "bank";
}
export function isFlashcard(c: AnyContent): c is FlashcardContent {
  return c.type === "flashcard";
}
export function isWritten(c: AnyContent): c is WrittenContent {
  return c.type === "written";
}
export function isOsce(c: AnyContent): c is OsceContent {
  return c.type === "osce";
}
export function isVideo(c: AnyContent): c is VideoContent {
  return c.type === "video";
}
export function isMixed(c: AnyContent): c is MixedContent {
  return c.type === "mixed";
}

/* ── Engine metadata helpers ────────────────────────────────────────── */

/**
 * Built-in engine metadata. Each field can be overridden per-instance via
 * `osler.config.json` → `engines.<id>.{label,singular,color,icon}`. The
 * override-aware accessor is `getEngineMeta(type)`; import `ENGINE_META`
 * directly only when you intentionally want the built-in defaults.
 */
export const ENGINE_META: Record<
  EngineType,
  { label: string; singular: string; color: string; icon: string }
> = {
  quiz: { label: "Quiz", singular: "Quiz", color: "oklch(0.62 0.16 250)", icon: "clipboard" },
  bank: {
    label: "Question Bank",
    singular: "Bank",
    color: "oklch(0.58 0.14 245)",
    icon: "book",
  },
  flashcard: {
    label: "Flashcards",
    singular: "Deck",
    color: "oklch(0.7 0.18 145)",
    icon: "layers",
  },
  written: {
    label: "Written",
    singular: "Set",
    color: "oklch(0.78 0.16 80)",
    icon: "pen-tool",
  },
  osce: { label: "OSCE", singular: "OSCE", color: "oklch(0.7 0.2 16)", icon: "activity" },
  library: { label: "Library", singular: "Article", color: "oklch(0.65 0.15 280)", icon: "book-open" },
  video: {
    label: "Videos",
    singular: "Video",
    color: "oklch(0.68 0.18 195)",
    icon: "video",
  },
  mixed: {
    label: "Mixed QBank",
    singular: "Mixed",
    color: "oklch(0.65 0.16 260)",
    icon: "layers",
  },
};

/**
 * Get engine metadata with any `osler.config` overrides applied. Falls back to
 * `ENGINE_META` defaults for any field the user has not overridden.
 */
export function getEngineMeta(type: EngineType): {
  label: string;
  singular: string;
  color: string;
  icon: string;
} {
  const base = ENGINE_META[type];
  const override = getEngineOverride(type);
  if (!override) return base;
  return {
    label: override.label ?? base.label,
    singular: override.singular ?? base.singular,
    color: override.color ?? base.color,
    icon: override.icon ?? base.icon,
  };
}
