/**
 * Osler content loader — fetches content from folder-based manifests.
 *
 * Content is stored under /osler-content/ in per-category folders:
 *   flashcard/, qbank/, osce/
 *
 * Each category has a manifest.json (auto-generated by scripts/generate-content-manifests.js)
 * describing a tree of ContentTreeNode objects. Leaf nodes correspond to folders
 * containing one or more .json data files whose arrays are merged on load.
 */

import type {
  AnyContent,
  BankContent,
  EngineType,
  FlashcardContent,
  OsceContent,
  QuizContent,
  WrittenContent,
  ContentTreeNode,
  CategoryManifest,
  Flashcard,
  FlashcardSubdeck,
  VideoContent,
} from "./types";
import { isEngineEnabled, getEngineOverride, enabledEngines } from "./config";
import { manifestUrl, contentFileUrl, packBasePath as resolvePackBasePath, resetCloudReachable } from "./content-url";

/* ── Category helpers ─────────────────────────────────────────────── */

const CATEGORY_PATHS: Record<string, string> = {
  quiz: "qbank",
  bank: "qbank",
  written: "qbank",
  flashcard: "flashcard",
  osce: "osce",
  library: "library",
  video: "videos",
};

function categoryFolder(type: EngineType): string {
  return CATEGORY_PATHS[type] ?? type;
}

/**
 * Base URL for a content node's folder (used to build precache URLs).
 */
export function packBasePath(node: ContentTreeNode): string {
  const folder = categoryFolder(node.type);
  return resolvePackBasePath(folder, node.path);
}

/**
 * All cacheable URLs for a leaf node: its data files plus any images in its
 * `images/` subfolder. Returns an empty array for branch nodes.
 */
export function nodeUrls(node: ContentTreeNode): string[] {
  if (node.items.length > 0) return [];
  const base = packBasePath(node);
  const urls = (node.files ?? []).map((f) => `${base}${f}`);
  for (const img of node.images ?? []) urls.push(`${base}images/${img}`);
  return urls;
}

/* ── Tree loading ─────────────────────────────────────────────────── */

/**
 * Load the category manifest (tree) for a given engine type.
 * Falls back to local URLs if the remote Worker is unreachable.
 */
export async function loadCategoryTree(type: EngineType): Promise<ContentTreeNode[]> {
  const folder = categoryFolder(type);
  let url = manifestUrl(folder);
  let res = await fetch(url, { cache: "no-store" });
  // If remote failed, reset cloud cache and retry with local URL
  if (!res.ok && url !== `/osler-content/${folder}/manifest.json`) {
    resetCloudReachable();
    url = `/osler-content/${folder}/manifest.json`;
    res = await fetch(url, { cache: "no-store" });
  }
  if (!res.ok) throw new Error(`Failed to load ${folder}/manifest.json: ${res.status}`);
  const manifest = (await res.json()) as CategoryManifest;
  return manifest.items;
}

/**
 * Flatten a content tree to a list of leaf nodes.
 */
export function flattenTree(nodes: ContentTreeNode[]): ContentTreeNode[] {
  const leaves: ContentTreeNode[] = [];
  function walk(list: ContentTreeNode[]) {
    for (const node of list) {
      if (node.items.length === 0) {
        leaves.push(node);
      } else {
        walk(node.items);
      }
    }
  }
  walk(nodes);
  return leaves;
}

/* ── Content loading from leaf folders ───────────────────────────── */

function engineTypeForCategory(type: EngineType, node: ContentTreeNode): EngineType {
  return node.type;
}

/**
 * Load content from a leaf node's folder by fetching all its .json data files
 * and merging their arrays. Falls back to local URLs if the Worker is unreachable.
 */
export async function loadNodeContent(node: ContentTreeNode): Promise<AnyContent> {
  const folder = categoryFolder(node.type);
  const dataFiles = (node.files ?? []).filter((f) => f.endsWith(".json"));
  if (dataFiles.length === 0) {
    throw new Error(`No JSON data files in ${node.path}`);
  }

  const base = contentFileUrl(folder, node.path);
  const results = await Promise.all(
    dataFiles.map(async (file) => {
      let res = await fetch(`${base}${file}`, { cache: "no-store" });
      // If remote failed, reset cloud cache and retry with local URL
      if (!res.ok) {
        const localBase = `/osler-content/${folder}/${node.path}`;
        if (base !== localBase) {
          resetCloudReachable();
          res = await fetch(`${localBase}${file}`, { cache: "no-store" });
        }
      }
      if (!res.ok) throw new Error(`Failed to load ${base}${file}: ${res.status}`);
      return (await res.json()) as Record<string, unknown>;
    })
  );

  // Merge all data arrays and preserve scalar fields like `type`
  const merged: Record<string, unknown[]> = {};
  for (const data of results) {
    for (const [key, val] of Object.entries(data)) {
      if (Array.isArray(val)) {
        if (!merged[key]) merged[key] = [];
        merged[key].push(...val);
      } else if (typeof val === "string" && key === "type") {
        // Preserve explicit `type` field from data file
        merged[key] = [val] as unknown[];
      }
    }
  }

  return buildContent(node, merged);
}

/**
 * Build an AnyContent object from a leaf node and merged data arrays.
 */
function buildContent(node: ContentTreeNode, data: Record<string, unknown[]>): AnyContent {
  // Use explicit `type` from data file if present, otherwise fall back to node.type
  const explicitType = data.type?.[0] as EngineType | undefined;
  const nodeType = explicitType || node.type;

  const meta = {
    uid: node.uid,
    title: node.title,
    description: `Content pack: ${node.title}`,
    lang: node.lang ?? "en",
  };

  switch (nodeType) {
    case "flashcard": {
      const cards = (data.cards ?? []) as Flashcard[];
      // If this node has children (branch node), they become subdecks
      const subdecks: FlashcardSubdeck[] | undefined = node.items.length > 0
        ? node.items.map((child) => ({
            id: child.uid,
            title: child.title,
            parentId: node.uid,
          }))
        : undefined;
      return { meta, type: "flashcard", cards, subdecks } as FlashcardContent;
    }
    case "quiz":
      return { meta, type: "quiz", questions: data.questions ?? [] } as QuizContent;
    case "bank":
      return { meta, type: "bank", passages: data.passages ?? [] } as BankContent;
    case "written":
      return { meta, type: "written", prompts: data.prompts ?? [] } as WrittenContent;
    case "osce":
      return { meta, type: "osce", stations: data.stations ?? [] } as OsceContent;
    case "video":
      return { meta, type: "video", videos: data.videos ?? [] } as VideoContent;
    default:
      throw new Error(`Unknown content type: ${nodeType}`);
  }
}

/* ── High-level loading ───────────────────────────────────────────── */

/**
 * Walk all category manifests and load all leaf content.
 * Returns both flat items list and per-category trees.
 */
export async function loadAllContent(): Promise<{
  items: Array<{ node: ContentTreeNode; content: AnyContent | null }>;
  trees: Record<string, ContentTreeNode[]>;
}> {
  // Filter out disabled engine plugins — only iterate engines enabled in osler.config.
  // Library articles use .md files loaded via articles.ts, not JSON — skip them here.
  const types = enabledEngines().filter((t) => t !== "library");
  const folders = new Set(types.map(categoryFolder));
  const allLeaves: ContentTreeNode[] = [];
  const trees: Record<string, ContentTreeNode[]> = {};

  for (const folder of folders) {
    try {
      let url = manifestUrl(folder);
      let res = await fetch(url, { cache: "no-store" });
      // If remote failed, reset cloud cache and retry with local URL
      if (!res.ok && url !== `/osler-content/${folder}/manifest.json`) {
        resetCloudReachable();
        url = `/osler-content/${folder}/manifest.json`;
        res = await fetch(url, { cache: "no-store" });
      }
      if (!res.ok) continue;
      const manifest = (await res.json()) as CategoryManifest;

      // For multi-type folders (qbank hosts quiz, bank, written), store the
      // same tree under every engine type that maps to this folder so the UI
      // can look up trees[engineType] for any qbank type.
      const qbankTypes: EngineType[] = ["quiz", "bank", "written"];
      if (folder === "qbank") {
        for (const et of qbankTypes) {
          if (types.includes(et)) trees[et] = manifest.items;
        }
      } else {
        let engineType: EngineType;
        if (folder === "flashcard") engineType = "flashcard";
        else if (folder === "osce") engineType = "osce";
        else if (folder === "videos") engineType = "video";
        else if (folder === "library") engineType = "library";
        else engineType = "quiz";
        trees[engineType] = manifest.items;
      }

      const leaves = flattenTree(manifest.items);
      allLeaves.push(...leaves);
    } catch {
      // ignore missing manifests
    }
  }

  const items = await Promise.all(
    allLeaves.map(async (node) => {
      try {
        const content = await loadNodeContent(node);
        return { node, content };
      } catch (e) {
        console.warn(`Failed to load ${node.path}:`, e);
        return { node, content: null };
      }
    })
  );
  return { items, trees };
}

/**
 * Load a single content pack by its node uid.
 */
export async function loadContentByUid(uid: string): Promise<AnyContent> {
  // Only search engines that are enabled in osler.config.
  // Library articles use .md files loaded via articles.ts, not JSON — skip them here.
  const types = enabledEngines().filter((t) => t !== "library");
  const folders = new Set(types.map(categoryFolder));

  for (const folder of folders) {
    try {
      let url = manifestUrl(folder);
      let res = await fetch(url, { cache: "no-store" });
      // If remote failed, reset cloud cache and retry with local URL
      if (!res.ok && url !== `/osler-content/${folder}/manifest.json`) {
        resetCloudReachable();
        url = `/osler-content/${folder}/manifest.json`;
        res = await fetch(url, { cache: "no-store" });
      }
      if (!res.ok) continue;
      const manifest = (await res.json()) as CategoryManifest;
      const found = findNodeByUid(manifest.items, uid);
      if (found) {
        return loadNodeContent(found);
      }
    } catch {
      continue;
    }
  }
  throw new Error(`Content not found: ${uid}`);
}

/**
 * Search a tree for a node by uid.
 */
function findNodeByUid(nodes: ContentTreeNode[], uid: string): ContentTreeNode | null {
  for (const node of nodes) {
    if (node.uid === uid) return node;
    if (node.items.length > 0) {
      const found = findNodeByUid(node.items, uid);
      if (found) return found;
    }
  }
  return null;
}

/**
 * Convert a ContentTreeNode to a simple object for passing as props.
 * (Keeps interface compatibility where ManifestItem was used.)
 */
export function nodeToItem(node: ContentTreeNode): {
  uid: string;
  type: EngineType;
  title: string;
  path: string;
} {
  return {
    uid: node.uid,
    type: node.type,
    title: node.title,
    path: node.path,
  };
}

/* ── Type guards ────────────────────────────────────────────────────── */
export function isQuiz(c: AnyContent): c is QuizContent {
  return c.type === "quiz";
}
export function isBank(c: AnyContent): c is BankContent {
  return c.type === "bank";
}
export function isFlashcard(c: AnyContent): c is FlashcardContent {
  return c.type === "flashcard";
}
export function isWritten(c: AnyContent): c is WrittenContent {
  return c.type === "written";
}
export function isOsce(c: AnyContent): c is OsceContent {
  return c.type === "osce";
}
export function isVideo(c: AnyContent): c is VideoContent {
  return c.type === "video";
}

/* ── Engine metadata helpers ────────────────────────────────────────── */

/**
 * Built-in engine metadata. Each field can be overridden per-instance via
 * `osler.config.json` → `engines.<id>.{label,singular,color,icon}`. The
 * override-aware accessor is `getEngineMeta(type)`; import `ENGINE_META`
 * directly only when you intentionally want the built-in defaults.
 */
export const ENGINE_META: Record<
  EngineType,
  { label: string; singular: string; color: string; icon: string }
> = {
  quiz: { label: "Quiz", singular: "Quiz", color: "oklch(0.62 0.16 250)", icon: "clipboard" },
  bank: {
    label: "Question Bank",
    singular: "Bank",
    color: "oklch(0.58 0.14 245)",
    icon: "book",
  },
  flashcard: {
    label: "Flashcards",
    singular: "Deck",
    color: "oklch(0.7 0.18 145)",
    icon: "layers",
  },
  written: {
    label: "Written",
    singular: "Set",
    color: "oklch(0.78 0.16 80)",
    icon: "pen-tool",
  },
  osce: { label: "OSCE", singular: "OSCE", color: "oklch(0.7 0.2 16)", icon: "activity" },
  library: { label: "Library", singular: "Article", color: "oklch(0.65 0.15 280)", icon: "book-open" },
  video: {
    label: "Videos",
    singular: "Video",
    color: "oklch(0.68 0.18 195)",
    icon: "video",
  },
};

/**
 * Get engine metadata with any `osler.config` overrides applied. Falls back to
 * `ENGINE_META` defaults for any field the user has not overridden.
 */
export function getEngineMeta(type: EngineType): {
  label: string;
  singular: string;
  color: string;
  icon: string;
} {
  const base = ENGINE_META[type];
  const override = getEngineOverride(type);
  if (!override) return base;
  return {
    label: override.label ?? base.label,
    singular: override.singular ?? base.singular,
    color: override.color ?? base.color,
    icon: override.icon ?? base.icon,
  };
}
