/**
 * Osler video loader — fetches video metadata from folder-based manifests.
 *
 * Mirrors `articles.ts`: the manifest tree lives at `/osler-content/videos/manifest.json`
 * (auto-generated by scripts/generate-content-manifests.js). Each leaf folder holds
 * one or more JSON files whose `videos` arrays are merged on load.
 *
 * A small JSON file per video means:
 *  - Adding a new video = drop a `.json` file in the right folder + re-run the manifest script
 *  - No central database, no migrations, no rebuild of the SPA
 *  - Same content-resolving logic as flashcards / OSCE / library
 */

import { loadCategoryTree, flattenTree } from "./content";
import { contentFileUrl } from "./content-url";
import type {
  ContentTreeNode,
  ContentLang,
  VideoResource,
  VideoContent,
} from "./types";

function videoFileUrl(relativePath: string): string {
  return contentFileUrl("videos", relativePath);
}

/* ── Tiny cache ─────────────────────────────────────────────────────── */

let treeCache: ContentTreeNode[] | null = null;
const leafVideoCache = new Map<string, VideoResource[]>();

/* ── Tree loading ──────────────────────────────────────────────────── */

/** Load the videos content tree. Cached after first call. */
export async function loadVideoTree(): Promise<ContentTreeNode[]> {
  if (treeCache) return treeCache;
  treeCache = await loadCategoryTree("video");
  return treeCache;
}

/** List all leaf nodes in the videos tree (flattened). */
export async function listVideoLeafNodes(): Promise<ContentTreeNode[]> {
  const tree = await loadVideoTree();
  return flattenTree(tree);
}

/* ── Video metadata loading ────────────────────────────────────────── */

/**
 * Fetch and merge the `videos` arrays from every JSON file in a leaf node.
 * Returns the merged list — safe to call multiple times (cached per-leaf).
 */
export async function loadNodeVideos(node: ContentTreeNode): Promise<VideoResource[]> {
  if (leafVideoCache.has(node.uid)) {
    return leafVideoCache.get(node.uid)!;
  }
  const files = node.files ?? [];
  const results = await Promise.all(
    files.map(async (file) => {
      const res = await fetch(videoFileUrl(`${node.path}${file}`), { cache: "no-store" });
      if (!res.ok) return [] as VideoResource[];
      const data = (await res.json()) as { videos?: VideoResource[] };
      return Array.isArray(data.videos) ? data.videos : [];
    }),
  );
  const merged = results.flat();
  leafVideoCache.set(node.uid, merged);
  return merged;
}

/** Return all videos across all leaf nodes (flattened). */
export async function listAllVideos(): Promise<Array<VideoResource & { nodeUid: string; nodePath: string }>> {
  const leaves = await listVideoLeafNodes();
  const all: Array<VideoResource & { nodeUid: string; nodePath: string }> = [];
  for (const leaf of leaves) {
    const videos = await loadNodeVideos(leaf);
    for (const v of videos) {
      all.push({
        ...v,
        nodeUid: leaf.uid,
        nodePath: leaf.path,
        lang: v.lang ?? leaf.lang ?? "en",
      });
    }
  }
  return all;
}

/**
 * Find a single video by id across every leaf folder.
 * Useful for "open this video" deep links.
 */
export async function findVideoById(
  id: string,
): Promise<(VideoResource & { nodeUid: string; nodePath: string }) | null> {
  const all = await listAllVideos();
  return all.find((v) => v.id === id) ?? null;
}

/** Search videos by title, specialty, instructor, or tags. */
export async function searchVideos(query: string): Promise<Array<VideoResource & { nodeUid: string; nodePath: string }>> {
  const q = query.trim().toLowerCase();
  const all = await listAllVideos();
  if (!q) return all;
  return all.filter((v) => {
    const hay = `${v.title} ${v.specialty ?? ""} ${v.topic ?? ""} ${v.instructor ?? ""} ${(v.tags ?? []).join(" ")} ${v.description ?? ""}`.toLowerCase();
    return hay.includes(q);
  });
}

/** Clear all caches (used by the manifest regenerate flow if any). */
export function clearVideoCache(): void {
  treeCache = null;
  leafVideoCache.clear();
}

/* ── Helpers ───────────────────────────────────────────────────────── */

/** Format a duration in seconds as `M:SS` or `H:MM:SS`. */
export function formatDuration(seconds: number | undefined): string {
  if (!seconds || seconds <= 0) return "--:--";
  const s = Math.floor(seconds % 60);
  const m = Math.floor((seconds / 60) % 60);
  const h = Math.floor(seconds / 3600);
  const ss = s < 10 ? `0${s}` : `${s}`;
  if (h > 0) {
    const mm = m < 10 ? `0${m}` : `${m}`;
    return `${h}:${mm}:${ss}`;
  }
  return `${m}:${ss}`;
}

/**
 * Resolve the poster/thumbnail URL for a video.
 * Falls back to a YouTube thumbnail when `thumbnail` is omitted.
 */
export function resolveThumbnail(video: Pick<VideoResource, "thumbnail" | "source">): string {
  if (video.thumbnail) return video.thumbnail;
  if (video.source?.type === "youtube" && video.source.id) {
    // hqdefault is always available; standard 480x360 thumbnail
    return `https://i.ytimg.com/vi/${video.source.id}/hqdefault.jpg`;
  }
  return "";
}

/** Helper: detect if a video source is a YouTube video. */
export function isYouTube(video: VideoResource): boolean {
  return video.source?.type === "youtube" && Boolean(video.source.id);
}
