import {
  GraduationCap,
  Clock,
  FileText,
  CheckCircle2,
  BarChart2,
  Sliders,
  MessageSquareWarning,
  Flag,
  Library,
  BookOpenText,
  Highlighter,
  Type,
  CloudDownload,
  Bookmark,
  BookmarkCheck,
  Plus,
  Sparkles,
  Layers,
  Play,
  Wrench,
  Sun,
  Zap,
  AlignLeft,
  ListChecks,
  type LucideIcon,
} from "lucide-react";
import type { StringKey } from "@/lib/osler/i18n";

export type TourId = "qbank-hub" | "qbank-session" | "library";

export interface WalkthroughStep {
  id: string;
  targetSelector: string;
  titleKey: StringKey;
  subtitleKey: StringKey;
  /** Optional deeper teaching line rendered under the subtitle. */
  descriptionKey?: StringKey;
  /** Optional coach tip rendered as a highlighted callout. */
  tipKey?: StringKey;
  mainIcon: LucideIcon;
  preferredPlacement?: "top" | "bottom" | "left" | "right" | "auto";
  highlightPadding?: number;
  highlightRadius?: number;
  /** Tab id forwarded to the consumer's onAction when the step is entered
      (hub tours use it to switch tabs). */
  onEnterTab?: string;
  /** Action key forwarded to the consumer's onAction when the step is
      entered — puts the UI in the state the step teaches (open/close a
      dialog or panel) so Next-button users get the same tour as clickers. */
  onEnterAction?: string;
  /** Auto-advance past this step when its target isn't on screen (conditional
      dialog sections, platform-only toggles). Re-checked at two beats so tab
      switches, navigation and content fetches get a chance to mount it. */
  skipIfMissing?: boolean;
}

/** Card eyebrow label per tour. */
export const TOUR_META: Record<TourId, { badgeKey: StringKey }> = {
  "qbank-hub": { badgeKey: "walkthrough.qbankHub.badge" },
  "qbank-session": { badgeKey: "walkthrough.qbank.badge" },
  library: { badgeKey: "walkthrough.library.badge" },
};

export const QBANK_HUB_STEPS: WalkthroughStep[] = [
  {
    id: "qbank-hub-create-tab",
    targetSelector: "[data-walkthrough='qbank-create-tab-btn']",
    titleKey: "walkthrough.qbankHub.step1.title",
    subtitleKey: "walkthrough.qbankHub.step1.subtitle",
    mainIcon: Plus,
    preferredPlacement: "bottom",
    highlightPadding: 6,
    highlightRadius: 10,
    onEnterTab: "create",
  },
  {
    id: "qbank-hub-create-mode",
    targetSelector: "[data-walkthrough='qbank-create-mode']",
    titleKey: "walkthrough.qbankHub.step2.title",
    subtitleKey: "walkthrough.qbankHub.step2.subtitle",
    descriptionKey: "walkthrough.qbankHub.step2.desc",
    tipKey: "walkthrough.qbankHub.step2.tip",
    mainIcon: Sparkles,
    preferredPlacement: "bottom",
    highlightPadding: 8,
    highlightRadius: 14,
    skipIfMissing: true,
  },
  {
    id: "qbank-hub-create-start",
    targetSelector: "[data-walkthrough='qbank-create-start']",
    titleKey: "walkthrough.qbankHub.step3.title",
    subtitleKey: "walkthrough.qbankHub.step3.subtitle",
    descriptionKey: "walkthrough.qbankHub.step3.desc",
    mainIcon: Play,
    preferredPlacement: "top",
    highlightPadding: 8,
    highlightRadius: 14,
    skipIfMissing: true,
  },
  {
    id: "qbank-hub-tracker-tab",
    targetSelector: "[data-walkthrough='qbank-tracker-tab-btn']",
    titleKey: "walkthrough.qbankHub.step4.title",
    subtitleKey: "walkthrough.qbankHub.step4.subtitle",
    mainIcon: BarChart2,
    preferredPlacement: "bottom",
    highlightPadding: 6,
    highlightRadius: 10,
    onEnterTab: "tracker",
  },
  {
    id: "qbank-hub-packs",
    targetSelector: "[data-walkthrough='qbank-packs']",
    titleKey: "walkthrough.qbankHub.step5.title",
    subtitleKey: "walkthrough.qbankHub.step5.subtitle",
    descriptionKey: "walkthrough.qbankHub.step5.desc",
    tipKey: "walkthrough.qbankHub.step5.tip",
    mainIcon: GraduationCap,
    preferredPlacement: "top",
    highlightPadding: 8,
    highlightRadius: 16,
    onEnterTab: "content",
  },
  {
    id: "qbank-hub-launch-mode",
    targetSelector: "[data-walkthrough='launch-mode']",
    titleKey: "walkthrough.qbankHub.step6.title",
    subtitleKey: "walkthrough.qbankHub.step6.subtitle",
    mainIcon: Sparkles,
    preferredPlacement: "bottom",
    highlightPadding: 8,
    highlightRadius: 14,
    // Reached via Next without a pack click — open the launch dialog on the
    // first pack so the dialog section of the tour can play out.
    onEnterAction: "open-launch-dialog",
    skipIfMissing: true,
  },
  {
    id: "qbank-hub-launch-chapters",
    targetSelector: "[data-walkthrough='launch-chapters']",
    titleKey: "walkthrough.qbankHub.step7.title",
    subtitleKey: "walkthrough.qbankHub.step7.subtitle",
    descriptionKey: "walkthrough.qbankHub.step7.desc",
    mainIcon: BookmarkCheck,
    preferredPlacement: "bottom",
    highlightPadding: 8,
    highlightRadius: 14,
    onEnterAction: "open-launch-dialog",
    skipIfMissing: true,
  },
  {
    id: "qbank-hub-launch-filters",
    targetSelector: "[data-walkthrough='launch-filters']",
    titleKey: "walkthrough.qbankHub.step8.title",
    subtitleKey: "walkthrough.qbankHub.step8.subtitle",
    descriptionKey: "walkthrough.qbankHub.step8.desc",
    mainIcon: Flag,
    preferredPlacement: "bottom",
    highlightPadding: 8,
    highlightRadius: 14,
    onEnterAction: "open-launch-dialog",
    skipIfMissing: true,
  },
  {
    id: "qbank-hub-launch-count",
    targetSelector: "[data-walkthrough='launch-count']",
    titleKey: "walkthrough.qbankHub.step9.title",
    subtitleKey: "walkthrough.qbankHub.step9.subtitle",
    descriptionKey: "walkthrough.qbankHub.step9.desc",
    mainIcon: Layers,
    preferredPlacement: "top",
    highlightPadding: 8,
    highlightRadius: 14,
    onEnterAction: "open-launch-dialog",
    skipIfMissing: true,
  },
  {
    id: "qbank-hub-launch-start",
    targetSelector: "[data-walkthrough='launch-start']",
    titleKey: "walkthrough.qbankHub.step10.title",
    subtitleKey: "walkthrough.qbankHub.step10.subtitle",
    descriptionKey: "walkthrough.qbankHub.step10.desc",
    tipKey: "walkthrough.qbankHub.step10.tip",
    mainIcon: Play,
    preferredPlacement: "top",
    highlightPadding: 8,
    highlightRadius: 12,
    onEnterAction: "open-launch-dialog",
    skipIfMissing: true,
  },
];

export const QBANK_SESSION_STEPS: WalkthroughStep[] = [
  {
    id: "qbank-session-bar",
    targetSelector: "[data-walkthrough='qbank-session-bar']",
    titleKey: "walkthrough.qbank.step1.title",
    subtitleKey: "walkthrough.qbank.step1.subtitle",
    descriptionKey: "walkthrough.qbank.step1.desc",
    mainIcon: Clock,
    preferredPlacement: "bottom",
    highlightPadding: 6,
    highlightRadius: 12,
  },
  {
    id: "qbank-question-stem",
    targetSelector: "[data-walkthrough='qbank-question-stem']",
    titleKey: "walkthrough.qbank.step2.title",
    subtitleKey: "walkthrough.qbank.step2.subtitle",
    mainIcon: FileText,
    preferredPlacement: "bottom",
    highlightPadding: 8,
    highlightRadius: 14,
    skipIfMissing: true,
  },
  {
    id: "qbank-options",
    targetSelector: "[data-walkthrough='qbank-options']",
    titleKey: "walkthrough.qbank.step3.title",
    subtitleKey: "walkthrough.qbank.step3.subtitle",
    tipKey: "walkthrough.qbank.step3.tip",
    mainIcon: CheckCircle2,
    preferredPlacement: "top",
    highlightPadding: 8,
    highlightRadius: 14,
    skipIfMissing: true,
  },
  {
    id: "qbank-annotate",
    targetSelector: "[data-walkthrough='qbank-annotate']",
    titleKey: "walkthrough.qbank.step4.title",
    subtitleKey: "walkthrough.qbank.step4.subtitle",
    mainIcon: Highlighter,
    preferredPlacement: "bottom",
    highlightPadding: 6,
    highlightRadius: 10,
    skipIfMissing: true,
  },
  {
    id: "qbank-settings",
    targetSelector: "[data-walkthrough='qbank-settings']",
    titleKey: "walkthrough.qbank.step5.title",
    subtitleKey: "walkthrough.qbank.step5.subtitle",
    mainIcon: Sliders,
    preferredPlacement: "bottom",
    highlightPadding: 6,
    highlightRadius: 10,
    // Leaving the settings-button step (either direction) puts the panel
    // away so the button itself is never spotlighted underneath it.
    onEnterAction: "close-quiz-settings",
  },
  {
    id: "qbank-settings-theme",
    targetSelector: "[data-walkthrough='quiz-settings-theme']",
    titleKey: "walkthrough.qbank.step6.title",
    subtitleKey: "walkthrough.qbank.step6.subtitle",
    mainIcon: Sun,
    preferredPlacement: "left",
    highlightPadding: 8,
    highlightRadius: 14,
    onEnterAction: "open-quiz-settings",
    skipIfMissing: true,
  },
  {
    id: "qbank-settings-typography",
    targetSelector: "[data-walkthrough='quiz-settings-typography']",
    titleKey: "walkthrough.qbank.step7.title",
    subtitleKey: "walkthrough.qbank.step7.subtitle",
    descriptionKey: "walkthrough.qbank.step7.desc",
    mainIcon: Type,
    preferredPlacement: "left",
    highlightPadding: 8,
    highlightRadius: 14,
    onEnterAction: "open-quiz-settings",
    skipIfMissing: true,
  },
  {
    id: "qbank-settings-behavior",
    targetSelector: "[data-walkthrough='quiz-settings-behavior']",
    titleKey: "walkthrough.qbank.step8.title",
    subtitleKey: "walkthrough.qbank.step8.subtitle",
    descriptionKey: "walkthrough.qbank.step8.desc",
    mainIcon: Zap,
    preferredPlacement: "left",
    highlightPadding: 8,
    highlightRadius: 14,
    onEnterAction: "open-quiz-settings",
    skipIfMissing: true,
  },
  {
    id: "qbank-settings-alignment",
    targetSelector: "[data-walkthrough='quiz-settings-alignment']",
    titleKey: "walkthrough.qbank.step9.title",
    subtitleKey: "walkthrough.qbank.step9.subtitle",
    mainIcon: AlignLeft,
    preferredPlacement: "left",
    highlightPadding: 8,
    highlightRadius: 14,
    // Hidden when the explanation layout is "split" — skipped gracefully.
    skipIfMissing: true,
  },
  {
    id: "qbank-submit",
    targetSelector: "[data-walkthrough='qbank-next']",
    titleKey: "walkthrough.qbank.step10.title",
    subtitleKey: "walkthrough.qbank.step10.subtitle",
    mainIcon: CheckCircle2,
    preferredPlacement: "top",
    highlightPadding: 8,
    highlightRadius: 12,
    onEnterAction: "close-quiz-settings",
  },
  {
    id: "qbank-navigator",
    targetSelector: "[data-walkthrough='qbank-nav-strip'], [data-walkthrough='qbank-nav-mobile']",
    titleKey: "walkthrough.qbank.step11.title",
    subtitleKey: "walkthrough.qbank.step11.subtitle",
    descriptionKey: "walkthrough.qbank.step11.desc",
    mainIcon: ListChecks,
    preferredPlacement: "right",
    highlightPadding: 6,
    highlightRadius: 12,
  },
  {
    id: "qbank-flag",
    targetSelector: "[data-walkthrough='qbank-flag']",
    titleKey: "walkthrough.qbank.step12.title",
    subtitleKey: "walkthrough.qbank.step12.subtitle",
    mainIcon: Flag,
    preferredPlacement: "top",
    highlightPadding: 6,
    highlightRadius: 10,
    skipIfMissing: true,
  },
  {
    id: "qbank-reporting",
    targetSelector: "[data-walkthrough='qbank-reporting']",
    titleKey: "walkthrough.qbank.step13.title",
    subtitleKey: "walkthrough.qbank.step13.subtitle",
    mainIcon: MessageSquareWarning,
    preferredPlacement: "top",
    highlightPadding: 6,
    highlightRadius: 10,
    skipIfMissing: true,
  },
  {
    id: "qbank-clinical-tools",
    targetSelector: "[data-walkthrough='qbank-tools']",
    titleKey: "walkthrough.qbank.step14.title",
    subtitleKey: "walkthrough.qbank.step14.subtitle",
    tipKey: "walkthrough.qbank.step14.tip",
    mainIcon: Wrench,
    preferredPlacement: "top",
    highlightPadding: 6,
    highlightRadius: 12,
    skipIfMissing: true,
  },
];

export const LIBRARY_STEPS: WalkthroughStep[] = [
  {
    id: "library-knowledge",
    targetSelector: "[data-walkthrough='library-tree']",
    titleKey: "walkthrough.library.step1.title",
    subtitleKey: "walkthrough.library.step1.subtitle",
    descriptionKey: "walkthrough.library.step1.desc",
    mainIcon: Library,
    preferredPlacement: "right",
    highlightPadding: 8,
    highlightRadius: 14,
  },
  {
    id: "library-toc",
    targetSelector: "[data-walkthrough='library-tabs']",
    titleKey: "walkthrough.library.step2.title",
    subtitleKey: "walkthrough.library.step2.subtitle",
    mainIcon: BookOpenText,
    preferredPlacement: "bottom",
    highlightPadding: 6,
    highlightRadius: 10,
    skipIfMissing: true,
  },
  {
    id: "library-tools",
    targetSelector: "[data-walkthrough='library-tools']",
    titleKey: "walkthrough.library.step3.title",
    subtitleKey: "walkthrough.library.step3.subtitle",
    tipKey: "walkthrough.library.step3.tip",
    mainIcon: Highlighter,
    preferredPlacement: "bottom",
    highlightPadding: 6,
    highlightRadius: 12,
    skipIfMissing: true,
  },
  {
    id: "library-display",
    targetSelector: "[data-walkthrough='library-display']",
    titleKey: "walkthrough.library.step4.title",
    subtitleKey: "walkthrough.library.step4.subtitle",
    descriptionKey: "walkthrough.library.step4.desc",
    mainIcon: Type,
    preferredPlacement: "bottom",
    highlightPadding: 6,
    highlightRadius: 10,
    skipIfMissing: true,
  },
  {
    id: "library-bookmark",
    targetSelector: "[data-walkthrough='library-bookmark']",
    titleKey: "walkthrough.library.step5.title",
    subtitleKey: "walkthrough.library.step5.subtitle",
    mainIcon: Bookmark,
    preferredPlacement: "bottom",
    highlightPadding: 6,
    highlightRadius: 10,
    skipIfMissing: true,
  },
  {
    id: "library-offline-pdf",
    targetSelector: "[data-walkthrough='library-export']",
    titleKey: "walkthrough.library.step6.title",
    subtitleKey: "walkthrough.library.step6.subtitle",
    descriptionKey: "walkthrough.library.step6.desc",
    mainIcon: CloudDownload,
    preferredPlacement: "bottom",
    highlightPadding: 6,
    highlightRadius: 10,
    skipIfMissing: true,
  },
  {
    id: "library-reporting",
    targetSelector: "[data-walkthrough='library-reporting']",
    titleKey: "walkthrough.library.step7.title",
    subtitleKey: "walkthrough.library.step7.subtitle",
    mainIcon: MessageSquareWarning,
    preferredPlacement: "bottom",
    highlightPadding: 6,
    highlightRadius: 10,
    skipIfMissing: true,
  },
];

export function getTourSteps(tour: TourId): WalkthroughStep[] {
  if (tour === "qbank-hub") return QBANK_HUB_STEPS;
  if (tour === "qbank-session") return QBANK_SESSION_STEPS;
  return LIBRARY_STEPS;
}


