#!/usr/bin/env bash
# build-deliverable.sh — Packages the rebased Osler project into a single zip
# placed in /home/z/my-project/download/.
#
# Includes:
#   - Full Next.js project source (src/, public/, prisma/, package.json, etc.)
#   - Sample Osler content packs
#   - OSLER_REBASE_README.md (rebase documentation)
#   - PATCH_NOTES_REBASE.md (concise change log)
#
# Excludes:
#   - node_modules/ (regenerated by `bun install`)
#   - .next/ build cache
#   - workspace/ (uploaded source zips)
#   - upload/ (original zip files)
#   - skills/, .zscripts/, dev.log, etc.

set -euo pipefail

PROJECT_ROOT="/home/z/my-project"
DOWNLOAD_DIR="${PROJECT_ROOT}/download"
STAGING_DIR="${PROJECT_ROOT}/.rebase-staging"
PKG_NAME="osler-rebased"
PKG_DIR="${STAGING_DIR}/${PKG_NAME}"
OUTPUT_ZIP="${DOWNLOAD_DIR}/${PKG_NAME}.zip"

echo "[1/5] Cleaning previous staging + zip…"
rm -rf "${STAGING_DIR}"
rm -f "${OUTPUT_ZIP}"
mkdir -p "${PKG_DIR}"
mkdir -p "${DOWNLOAD_DIR}"

echo "[2/5] Copying project files to staging…"
cd "${PROJECT_ROOT}"

# Copy top-level config files
cp package.json bun.lock postcss.config.mjs tailwind.config.ts tsconfig.json \
   next.config.ts components.json eslint.config.mjs Caddyfile \
   OSLER_REBASE_README.md PATCH_NOTES_REBASE.md \
   "${PKG_DIR}/" 2>/dev/null || true

# Copy directories we want in the deliverable
for d in src public prisma examples scripts; do
  if [ -d "${PROJECT_ROOT}/${d}" ]; then
    cp -r "${PROJECT_ROOT}/${d}" "${PKG_DIR}/"
  fi
done

# Create a focused .gitignore
cat > "${PKG_DIR}/.gitignore" << 'GITEOF'
# dependencies
node_modules/
.pnp
.pnp.js

# next.js
.next/
out/
build/
dist/

# misc
.DS_Store
*.pem
.vscode/
.idea/

# debug
npm-debug.log*
yarn-debug.log*
yarn-error.log*
dev.log
server.log

# env files
.env
.env.local
.env.development.local
.env.test.local
.env.production.local

# typescript
*.tsbuildinfo
next-env.d.ts

# prisma
prisma/dev.db
prisma/*.db-journal

# osler local data
osler-progress-v1
osler-ai-chat-v1
osler-written-drafts
GITEOF

# Add a .nvmrc matching the project
echo "22" > "${PKG_DIR}/.nvmrc"

echo "[3/5] Removing workspace/upload/skills artifacts from staging if present…"
rm -rf "${PKG_DIR}/workspace" "${PKG_DIR}/upload" "${PKG_DIR}/download" \
       "${PKG_DIR}/skills" "${PKG_DIR}/.zscripts" "${PKG_DIR}/.rebase-staging" \
       "${PKG_DIR}/dev.log" "${PKG_DIR}/server.log" 2>/dev/null || true

# Verify content packs are in place
if [ ! -f "${PKG_DIR}/public/osler-content/manifest.json" ]; then
  echo "ERROR: Sample content missing from staging!"
  exit 1
fi

echo "[4/5] Zipping…"
cd "${STAGING_DIR}"
zip -qr "${OUTPUT_ZIP}" "${PKG_NAME}" \
  -x "*/node_modules/*" \
  -x "*/.next/*" \
  -x "*/.git/*" \
  -x "*/dev.log" \
  -x "*/server.log"

echo "[5/5] Done. Output:"
ls -lh "${OUTPUT_ZIP}"
echo ""
echo "Top-level contents of zip:"
unzip -l "${OUTPUT_ZIP}" | head -25
echo "..."
echo "Total entries: $(unzip -l "${OUTPUT_ZIP}" | tail -1)"
